name: build
on:
  pull_request:
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
jobs:
  build-switch:
    runs-on: ubuntu-latest
    container:
      image: devkitpro/devkita64:latest
    steps:
    # - name: Install dependencies
    #   run: |
    #     sudo apt-get update
    #     sudo apt-get install -y ninja-build
    - uses: actions/checkout@v3
      with:
        submodules: true
    - name: ccache
      uses: hendrikmuhs/ccache-action@v1.2
      with:
        key: ${{ runner.os }}-switch-ccache
    - name: Build
      run: |
        ls
        cd lib/Atmosphere-libs/libstratosphere
        make
        cd ../../..
        make dist
    - name: Upload build
      uses: actions/upload-artifact@v3
      with:
        name: MissionControl
        path: |
          dist/*.zip
          