name: build
on:
  pull_request:
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
jobs:
  build-switch:
    runs-on: ubuntu-latest
    container:
      image: devkitpro/devkita64:latest
    steps:
    - uses: actions/checkout@v3
      with:
        submodules: true
    - name: Build
      run: |
        ls
        cd lib/Atmosphere-libs/libstratosphere
        make -j
        cd ../../..
        make dist
    - name: Upload build
      uses: actions/upload-artifact@v3
      with:
        name: MissionControl
        path: |
          dist/*.zip
          